DROP SEQUENCE hair_kind_no_seq;
DROP SEQUENCE HAIR_NO_SEQ;
DROP SEQUENCE DESGINER_NO_SEQ;
DROP SEQUENCE EVENT_NO_SEQ;
DROP SEQUENCE BOOK_NO_SEQ;


/* 헤어 분류 번호 */
CREATE SEQUENCE HAIR_KIND_NO_SEQ
	START WITH 1
	INCREMENT BY 1
	NOCACHE;

CREATE OR REPLACE TRIGGER HAIR_KIND_NO_SEQ
BEFORE INSERT ON HAIR_KIND
FOR EACH ROW 
BEGIN 
	IF Inserting AND :NEW.KIND_NO IS NULL THEN 
		SELECT HAIR_KIND_NO_SEQ.NEXTVAL INTO :NEW.KIND_NO FROM DUAL;
	END IF;
END; 


/* 헤어 번호 */
CREATE SEQUENCE HAIR_NO_SEQ
	START WITH 1
	INCREMENT BY 1
	NOCACHE;

CREATE OR REPLACE TRIGGER HAIR_NO_SEQ
BEFORE INSERT ON HAIR
FOR EACH ROW 
BEGIN 
	IF Inserting AND :NEW.HAIR_NO IS NULL THEN 
		SELECT HAIR_NO_SEQ.NEXTVAL INTO :NEW.HAIR_NO FROM DUAL;
	END IF;
END; 


/* 디자이너 번호 */
CREATE SEQUENCE DESGINER_NO_SEQ
	START WITH 1
	INCREMENT BY 1
	NOCACHE;

CREATE OR REPLACE TRIGGER DESGINER_NO_SEQ
BEFORE INSERT ON DESIGNER
FOR EACH ROW 
BEGIN 
	IF Inserting AND :NEW.DE_NO IS NULL THEN 
		SELECT DESGINER_NO_SEQ.NEXTVAL INTO :NEW.DE_NO FROM DUAL;
	END IF;
END; 



/* 이벤트 번호 */
CREATE SEQUENCE EVENT_NO_SEQ
	START WITH 1
	INCREMENT BY 1
	NOCACHE;

CREATE OR REPLACE TRIGGER EVENT_NO_SEQ
BEFORE INSERT ON EVENT
FOR EACH ROW 
BEGIN 
	IF Inserting AND :NEW.EVENT_NO IS NULL THEN 
		SELECT EVENT_NO_SEQ.NEXTVAL INTO :NEW.EVENT_NO FROM DUAL;
	END IF;
END; 



/* 예약 번호 */
CREATE SEQUENCE BOOK_NO_SEQ
	START WITH 1
	INCREMENT BY 1
	NOCACHE;


CREATE OR REPLACE TRIGGER BOOK_NO_SEQ
BEFORE INSERT ON BOOKING
FOR EACH ROW 
BEGIN 
	IF Inserting AND :NEW.BOOK_NO IS NULL THEN 
		SELECT BOOK_NO_SEQ.NEXTVAL INTO :NEW.BOOK_NO FROM DUAL;
	END IF;
END; 
