/* GUEST_VIEW */
-- 회원 전체 목록 뽑기
-- 보안을 위해 비밀번호는 들고 오지 않았는데 뭐가 좋은지는 잘 모르겠음.
CREATE OR REPLACE VIEW GUEST_VIEW
AS
SELECT 
	GUEST_ID, GUEST_NAME, GUEST_BIRTHDAY, GUEST_PHONE, GUEST_GENDER, GUEST_JOIN_DATE, GUEST_NOTE, DEL_YN
	FROM GUEST;
	

/* ADMIN_VIEW */
CREATE OR REPLACE VIEW ADMIN_VIEW
AS
SELECT
	ADMIN_ID, ADMIN_PWD, ADMIN_NAME 
	FROM ADMIN;

/*QnA_VIEW*/
CREATE OR REPLACE VIEW QNA_VIEW
AS
SELECT
	q.QNA_NO, q.GUEST_ID, q.QNA_TITLE, q.QNA_FILE, q.QNA_REGDATE, q.RES_YN
	FROM QNA q JOIN GUEST g ON(g.GUEST_ID = q.GUEST_ID );

SELECT * FROM qna_view;


/* EVENT_MIN_VIEW */
-- 예약/주문시 콤보박스로 불러오기 위해 간략하게 조회
CREATE OR REPLACE VIEW EVENT_MIN_VIEW
AS
SELECT EVENT_NO, EVENT_NAME, EVENT_SALERATE, EVENT_START, EVENT_END FROM EVENT;
