/* GUEST_VIEW */
-- 회원 전체 목록 뽑기
-- 보안을 위해 비밀번호는 들고 오지 않았는데 뭐가 좋은지는 잘 모르겠음.
CREATE OR REPLACE VIEW GUEST_VIEW
AS
SELECT 
	GUEST_ID, GUEST_NAME, GUEST_BIRTHDAY, GUEST_PHONE, GUEST_GENDER, GUEST_JOIN_DATE, GUEST_NOTE, DEL_YN
	FROM GUEST;
	

/* ADMIN_VIEW */
CREATE OR REPLACE VIEW ADMIN_VIEW
AS
SELECT
	ADMIN_ID, ADMIN_PWD, ADMIN_NAME 
	FROM ADMIN;

