SELECT * FROM HAIR_BOARD;
SELECT * FROM HAIR_KIND;
SELECT * FROM HAIR;
--1.숏 
--2.미디움 
--3.롱
--4.man

INSERT INTO VALUES (HBOARD_CATENO,HBOARD_TITLE,HAIR_NO,HBOARD_CONTENT,HBOARD_PIC,HBOARD_REGDATE) VALUES (1, 's1', )
